{% set name = "asyncssh" %}
{% set version = "1.7.1" %}
{% set sha256 = "69b5712b17ddf94a4d44da3a71949d468906ef61f4d4767e276987e2e841e4da" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ronf/asyncssh/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py < 34]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: "AsyncSSH: Asynchronous SSHv2 client and server library"

extra:
  recipe-maintainers:
    - vamega
