{% set name = "asyncssh" %}
{% set version = "2.7.0" %}
{% set sha256 = "185013d8e67747c3c0f01b72416b8bd78417da1df48c71f76da53c607ef541b6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - python >=3.4
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: 'AsyncSSH: Asynchronous SSHv2 client and server library'

extra:
  recipe-maintainers:
    - vamega
