{% set name = "asyncssh" %}
{% set version = "1.12.0" %}
{% set sha256 = "311b7e580822f2ff0e0e492adb7e09cc31047afd8a23662c7e99ef0f6de631e3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ronf/asyncssh/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py < 34]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: "AsyncSSH: Asynchronous SSHv2 client and server library"

extra:
  recipe-maintainers:
    - vamega
