{% set name = "asyncssh" %}
{% set version = "1.13.3" %}
{% set sha256 = "e3ae3deabe837cecc01c6db43a48dcced51f6f3a7bbba82b5c38163402dc4163" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ronf/asyncssh/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py < 34]
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: "AsyncSSH: Asynchronous SSHv2 client and server library"

extra:
  recipe-maintainers:
    - vamega
