{% set name = "asyncssh" %}
{% set version = "2.1.0" %}
{% set sha256 = "13f2719858cce8d91b8c56c6373f9d7e3c2719ea6007e9cc5e35133ef189170e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ronf/asyncssh/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.4
    - setuptools
    - pip
  run:
    - python >=3.4
    - cryptography

test:
  imports:
    - asyncssh

about:
  home: https://github.com/ronf/asyncssh
  license: EPL-1.0
  summary: "AsyncSSH: Asynchronous SSHv2 client and server library"

extra:
  recipe-maintainers:
    - vamega
