# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KIKJM3yIBmrZaUzwC9vFQxXVgpHemk7h2MZ9H9+fLuGv6/O+icIsTZIJkFlaxezWlaZWote9jiUno2FZFec2Mi5KUUR2pcBmdI/V0Ivix1fKcBYhOGzR1TaBMTS0RjYWOMkgiCAg1BBGDIIRJCGCI+SSzZfX9CF1DUwy6jerv2oPF/komP7RdLBatcZYNLyFguWoFExPOQx0v6x2XH70bWmIZVD3bmEJY1OjqcE+ufe2Q6lSqGd7RHOrL/V90Q6o2Z3BJ4EF+fA/wpoBUQJbZCGDEr6H2+TYWc07gHf6dG6Iv86532bmy5RzeDEzb1qyqJhArIBy7n2dLMTwQeX7V6y3WV8pB/j8a1pSfwjLjQhxCyzcvFgZvZHeMaBQMKSk4LrlYWlr16whRHympaNZ/nEeHW2znO7L5jc2i1p5QxDzgd7n50Xw/x5EUIGLb9t12FDjkXpvQ+W6Ym421mWzPZZCNHLAzaY+eo8HpXhIypoGUxwwYs6PtUpa/Itwv75FCt8PGx50qXh4tMYZIuxowPfplhf7nOEONIfPaCEHdufDxdS97P5UzqvSCzbDLfV6rEimrX2vlIRy2cvdpP0+L0Jii5SRa5SLE4XxY12lSdk71QlNED63yhmlYwo+OEWiZTwOYzexRq6f1rZEi0AmANrnygJChl7Jo80If+9H5Bo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
