travis:
  secure:
    BINSTAR_TOKEN: ecwqCWJCK7ekk//+KKcFf1xlOoJuh3hlTXGIXWHmizaAWhiO5PaK5IxJHcOQYxhYGhchKlO7ttI6T3IVsArxTkBDxWYrOGIdbMYOLcoCr5GhlhEZRDfmG2qQDXzwo+v4o3zb9fHHkGl4yB7A2cv6KZ+A18IWD+smF2Njn8SpJU1sJVmwzPPYUsp/z4TQA5HTAEolYUcsFkU94TiiPKeng+7zTmRJ/DOuBwf8GgGVfTj9RPySS8YAamLIYCpoH4M+CGQi4B0GvUGyIQCA+AJGpX54Hlj1eLpY0qhRocwcebZTzQEHkFkly5nZRHQww0g8dgB50ILzHWxCmKpycJVubSgEzKIxpvP+ehV9lNOehTV0ej8Lbz1aPO29DriyKZfTdrjeDS6E4+al7ObPjbwbxylAzFLHv5liWeec908v8CVDDJz1r6pQQwMfeNvll4f4uO58FQCRth5e2ZVQPAAtoy+8GRAj0TqsPhZe6TiyMPBVYISm/JaV0Ho71rUqlIOS2J/ZagaeGkW/tXptZqOcWRcROlnC7cjXQ7x1JrYV75LNJiUmh3iqwX6DmwaUqU68xWirk0h7X6HM42kZb2corS7+YPo3HOEXZDkhYa4mw1n7ivUHfLCelj1RR7roLSbsj8jAfW1DH9xggArKhc/eLbs39zuxQRWI07sOGSY/96k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
